### ISSUE TITLE
Installing OTL in DX Seattle afflicts OTL in DXE8

### ISSUE THREAD

**Issue by PeterPanino** [gabr42/OmniThreadLibrary#43]
Although both packages are installed in different directories:

Delphi XE8: F:\Users\<username>\Documents\Embarcadero\Studio\16.0\CatalogRepository\OmniThreadLibrary-3.04b

Delphi X Seattle: F:\Users\<username>\Documents\Embarcadero\Studio\17.0\CatalogRepository\OmniThreadLibrary-3.04b

After having installed OTL in Delphi X Seattle with the GetIt package manager, when starting Delphi XE8 the following error message is displayed:

---
[Window Title]
Error
[Content]
Can't load package C:\Users\Public\Documents\Embarcadero\Studio\16.0\bpl\OmniThreadLibraryDesigntimeXE8.bpl.
Access violation at address 32E08791 in module 'bds.exe'. Read of address 00000010.
Do you want to attempt to load this package the next time a project is loaded?
[Yes] [No]
---

So it seems that OTL Seattle afflicts OTL XE8. Why? This should not be the case.

**Comment by gabr42** [comment]
Re: [OmniThreadLibrary] Installing OTL in DX Seattle afflicts OTL in DXE8 (#43)


I'll take a look as soon as I have Seattle installed, but this is really not under my control. You would have to ask Embarcadero ...

Primož





Although both packages are installed in different directories:
Delphi XE8: F:\Users<username>\Documents\Embarcadero\Studio\16.0\CatalogRepository\OmniThreadLibrary-3.04b
Delphi X Seattle: F:\Users<username>\Documents\Embarcadero\Studio\17.0\CatalogRepository\OmniThreadLibrary-3.04b
After having installed OTL in Delphi X Seattle with the GetIt package manager, when starting Delphi XE8 the following error message is displayed:
[Window Title]
Error
[Content]
Can't load package C:\Users\Public\Documents\Embarcadero\Studio\16.0\bpl\OmniThreadLibraryDesigntimeXE8.bpl.
Access violation at address 32E08791 in module 'bds.exe'. Read of address 00000010.
Do you want to attempt to load this package the next time a project is loaded?
[Yes] [No]
So it seems that OTL Seattle afflicts OTL XE8. Why? This should not be the case.

**Comment by gabr42** [comment]
I'm in contact with Embarcadero support regarding this issue. Will report back when more is known.

**Comment by gabr42** [comment]
From Embarcadero:

The problem seems to be that the packages are both in the %PATH% system variable with the same name “OmniThreadLibraryRuntimeXE8.bpl”. So the XE8 IDE finds first the 10 Seattle runtime library (as 10 Seattle has been installed later, it’s earlier in the %PATH%).

We’re working on a permanent solution for these case, as a workaround, the customers can override the Path in Environment Variables in XE8, and add “C:\Users\Public\Documents\Embarcadero\Studio\16.0\Bpl\” at the beginning.

From me:

This can work as a temporary fix. I'll make sure that Delphi 10 gets proper OmniThreadLibrary package names as soon as possible so this conflict will be resolved.
